[project]
name = "basic"
version = "0.1.0"
description = "Leet code patterns"
authors = [
    {name = "Jagan",email = "jaganadhg@outlook.com"}
]
license = {text = "Apache 2.0"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
